<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Zed.Web</PackageId>
    <Title>Zed.Web</Title>
    <AssemblyTitle>Zed.Web</AssemblyTitle>
    <Description>Zed.Web is a library which contains web-specific core application concepts</Description>
    <PackageReleaseNotes>Zed.Web is a library which contains web-specific core application concepts</PackageReleaseNotes>
    <Authors>ztepsic</Authors>
    <RequireLicenseAcceptance>false</RequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/ztepsic/zed.web</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ztepsic/zed.web</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>Zed Web</PackageTags>
    <Copyright>Copyright 2026</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Zed" />
  </ItemGroup>

</Project>
